namespace Whim;

/// <summary>
/// Creates a new workspace pinned to the given monitor, and shows it on that monitor.
/// </summary>
/// <param name="MonitorHandle">
/// The handle of the monitor to create the workspace on. Defaults to the active monitor.
/// </param>
/// <param name="Name">
/// The name of the new workspace. If <see langword="null"/> (the default), a numeric name is
/// generated by taking the first non-negative integer (starting from <c>0</c>) whose string
/// representation is not already used by an existing workspace.
/// </param>
public record CreateWorkspaceOnMonitorTransform(HMONITOR MonitorHandle = default, string? Name = null)
	: Transform<WorkspaceId>
{
	internal override Result<WorkspaceId> Execute(
		IContext ctx,
		IInternalContext internalCtx,
		MutableRootSector mutableRootSector
	)
	{
		// Resolve the target monitor and its index.
		HMONITOR monitorHandle =
			MonitorHandle == default ? mutableRootSector.MonitorSector.ActiveMonitorHandle : MonitorHandle;

		ImmutableArray<IMonitor> monitors = mutableRootSector.MonitorSector.Monitors;
		int monitorIndex = -1;
		for (int idx = 0; idx < monitors.Length; idx++)
		{
			if (monitors[idx].Handle == monitorHandle)
			{
				monitorIndex = idx;
				break;
			}
		}

		if (monitorIndex == -1)
		{
			return Result.FromError<WorkspaceId>(StoreErrors.MonitorNotFound(monitorHandle));
		}

		string name = Name ?? WorkspaceUtils.GenerateWorkspaceName(mutableRootSector.WorkspaceSector);

		// Create the workspace, pinned (sticky) to the target monitor.
		Result<WorkspaceId> addResult = ctx.Store.Dispatch(
			new AddWorkspaceTransform(Name: name, MonitorIndices: [monitorIndex])
		);
		if (!addResult.TryGet(out WorkspaceId workspaceId))
		{
			return addResult;
		}

		// Show the new workspace on the target monitor.
		Result<Unit> activateResult = ctx.Store.Dispatch(new ActivateWorkspaceTransform(workspaceId, monitorHandle));
		if (!activateResult.IsSuccessful)
		{
			return Result.FromError<WorkspaceId>(activateResult.Error!);
		}

		return workspaceId;
	}
}
